--DELETE FROM ""; BORRARA TODO LOS DATOS
--TRUNCATE TABLE ""; FORMATEARA TODO LOS ID DE LOS USUARIOS ADD

-- IMPORTARTE PORNER **WHERE** PARA NO BORRAR TODA LA BASE DE LOS DATOS

USER metro_cdmx;

DELETE FROM `stations`
WHERE id = 5 or id = 6;
